添加cmake文件

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -3,7 +3,7 @@ name: Build Linux
 on:
   push:
     tags:
-      - "v*.*"
+      - "v*.*.*"
   workflow_dispatch:
     inputs:
       name:
@@ -21,6 +21,15 @@ jobs:
           - ubuntu-22.04
           - ubuntu-24.04
     steps:
+      - name: Process Version
+        run: |
+          TAG_VERSION=$(echo "${{ env.VERSION }}" | sed 's/^[vV]//')
+          if ! [[ $TAG_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "version ${{ env.VERSION }} error."
+            exit 1
+          fi
+          echo "GITHUB_VERSION=$TAG_VERSION" >>$GITHUB_ENV
+
       - name: Checkout
         uses: actions/checkout@v6
 
@@ -30,44 +39,23 @@ jobs:
           sudo apt-get install -y qt5-qmake qt5-qmake-bin qtbase5-dev qtbase5-dev-tools
           sudo apt-get install -y libqt5core5a libqt5gui5 libqt5widgets5 libqt5network5 libqt5x11extras5-dev
           sudo apt-get install -y build-essential libopencv-dev libxtst-dev libxrandr-dev libx11-dev
+          sudo apt-get install -y cmake
 
-      - name: Build
+      - name: Build and Package
         run: |
-          /usr/bin/x86_64-linux-gnu-qmake
-          make -j$(nproc)
+          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
+          cmake --build build -j$(nproc)
+          cmake --build build --target package
+          mv build/screenshot.deb screenshot-${{ matrix.os }}.deb
+          mv build/screenshot.deb.sha256 screenshot-${{ matrix.os }}.deb.sha256
+          ls
 
-      - name: Print Depend
-        run: |
-          echo "=== apt installed libqt5 packages ==="
-          apt list --installed | grep libqt5 || true
-
-          echo "=== depends ==="
-          mkdir -p debian
-          touch debian/control
-          DEPENDS="$(dpkg-shlibdeps -O screenshot 2>/dev/null | awk -F 'Depends=' '{print $2}')"
-          echo "DEPENDS=$DEPENDS" >>$GITHUB_ENV
-          echo "Depends: $DEPENDS"
-
-      - name: Package deb
-        run: |
-          TAG_VERSION=$(echo "${{ env.VERSION }}" | sed 's/^[vV]//')
-          if grep -q '^Version:' package/linux/control; then
-            sed -i "/^Version:/c Version: $TAG_VERSION" package/linux/control
-          else
-            sed -i "/^Package:/a Version: $TAG_VERSION" package/linux/control
-          fi
-          if grep -q '^Depends:' package/linux/control; then
-            sed -i "/^Depends:/c Depends: ${{ env.DEPENDS }}" package/linux/control
-          else
-            sed -i "/^Maintainer:/a Depends: ${{ env.DEPENDS }}" package/linux/control
-          fi
-
-          make package -j
-          mv screenshot.deb screenshot-${{ matrix.os }}.deb
 
       - name: Upload deb
         uses: actions/upload-artifact@v6
         with:
           name: screenshot-${{ github.job }}-${{ matrix.os }}
-          path: screenshot-${{ matrix.os }}.deb
+          path: |
+            screenshot-${{ matrix.os }}.deb
+            screenshot-${{ matrix.os }}.deb.sha256
 
